name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: OTP ${{matrix.otp}}
    runs-on: ubuntu-latest
    container:
      image: erlang:${{matrix.otp}}
    strategy:
      matrix:
        otp:
          - 26
          - 25
          - 24
          - 23
          - 22
          - 21
          - 20
          - 19
          - 18
    steps:
      - uses: actions/checkout@v4
      - name: Compile
        run: rebar3 compile
      - name: Run tests
        run: rebar3 do eunit
