name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    container:
      image: maven:3-eclipse-temurin-${{ matrix.java }}
    strategy:
      fail-fast: false
      matrix:
        java:
          - 25
          - 21
          - 17
          - 11
    steps:
      - uses: actions/checkout@v4
      - name: Build with Maven
        run: mvn clean test jacoco:report coveralls:report -DrepoToken=${{ secrets.COVERALLS_TOKEN }}
