name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Node.js ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macox-latest
          - ubuntu-latest
          - windows-latest
        node:
          - 15.x
          - 14.x
          - 12.x
          - 10.x
          - 8.x
          - 6.x
          - 4.x
    steps:
    - uses: actions/checkout@v2
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm run lint
